# https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/MIME_types
_merge = "deep"

# Temporary override, text/javascript is the new universal MIME type as of May 2022
["text/javascript"]
  suffixes = ["js", "jsm", "mjs"]
