# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = 'deep'

### BGN: Structured Data ###
  license = 'https://im.youronly.one/p/legal-notice/'
### END: Structured Data ###

### BGN: Hugo module settings ###
### END: Hugo module settings ###

### BGN: Theme Settings ###
### END: Theme Settings ###

### BGN: Other Settings ###
  [analytics]
    enable = true
    position = 'head'       # head or body
    cfwebanalytics = '07a05e5302d1458da3561ce41791e284'       # https://cloudflare.com | 'privacy-first'
    counterdev = 'youronlyone'           # https://counter.dev | 'privacy-friendly'
    #microanalyticsio = 'ZwSg9rf6GA'     # https://microanalytics.io | 'privacy-first', 'green energy'
    #microsoftclarity = '63ddi0b99e'     # https://clarity.microsoft.com
    naver = '1375cb4224f1c40'                # https://analytics.naver.com for youronly.one
    #naver = '137a7c92882ac90'                # https://analytics.naver.com for im.youronly.one
    swetrix = 'bYdcXUajNvru'              # https://swetrix.com | 'privacy-first'

  [social]
    # See: https://github.com/gohugoio/hugo/pull/12234
    enable = true
    #facebook_authorid = ''                         # template-only
    ##codeberg = 'techmagus'                                   # username
    #codepen = ''                                    # username
    #deviantart = 'laibcoms'                                 # URL-name without @
    #email = 'contact@im.youronly.one'                                      # address@example.com
    facebook = 'YourOnly.ONE.ofcl'                                   # URL-name
    facebook_admin = '532996690,100042645428366,2308171266072912'                             # profile ID number and page admin to get domain insights
    facebook_app_id = '183794425326191'                            # app ID
    facebook_authorid = '2308171266072912'                          # user ID
    facebook_pageid = '339301830572387'                            # page ID
    github = 'techmagus'                                     # username
    gitlab = 'techmagus'                                     # username
    #googlescholar = ''                              # username
    #instagram = 'youronly.one.ofcl'                                  # username
    keybase = 'yukino'                                    # username
    ##keyoxide = 'youronly.one/?verify=keyoxide'                                   # URL
    #linkedin = 'youronlyone'                                   # URL-name
    mastodon = 'c.im/@youronlyone'                                   # example.com/@username
    #medium = 'youronly.one'                                     # username without @
    #pinterest = 'YourOnlyONEofcl'                                  # username
    pixelfed = 'pixelfed.social/@youronlyone'                                   # example.com/@username
    #reddit = 'Laibcoms'                                     # username
    #researchgate = ''                               # username
    #slideshare = ''                                 # username
    #stackoverflow = '306674'                              # user number
    #strava = 'faithfulathlete'                                     # URL-name or userID number
    #telegram = ''                                   # URL-name
    ##threads = 'youronly.one.ofcl'                                    # username without @
    tumblr = 't.youronly.one'                                     # URL
    twitter = 'YourOnlyONEofcl'                                    # username; do not include @-at
    twitter_creator = '@YourOnlyONEofcl'                            # @username
    wordpress = 'youronlyoneofcl.wordpress.com'                                  # URL
    youtube = 'YourOnlyONEofcl'                                    # username without @
### END: Other Settings ###
