#bitbucket = "techmagus"                                          #
codeberg = "techmagus"                                           #
#deviantart = "laibcoms"                                         # URL-name
ecency = "@youronlyone"                                             #
#email = "contact@youronly.one"                                              # email address; leave empty
facebook = "YourOnly.ONE.ofcl"                                           # URL-name
facebook_admin = "532996690,100042645428366,2308171266072912"                                     # profile ID number and page admin to get domain insights
facebook_appid = "183794425326191"                                     # app ID
facebook_authorid = "2308171266072912"                                  #
facebook_pageid = "339301830572387"                                    # FB page ID
github = "techmagus"                                             # username
gitlab = "techmagus"                                             # username
hive = "@youronlyone"                                               #
instagram = "YourOnly.One"                                          # username
keybase = "yukino"                                            # username
#linkedin = "youronlyone"                                           # URL-name
#linkedin_company = ""                                   # URL-name
#mastodon = "c.im/@youronlyone"                                           # example.com/@username
mastodon = "mastodon.social/@youronlyone"                                           # example.com/@username
#medium = ""                                             #
pinterest = "YourOnlyONEofcl"                                          # username
#quora = ""                                              # username
#reddit = "Laibcoms"                                             # username
#skype = ""                                              # username or email
#stackoverflow = "306674"                                      # user number
steemit = "@youronlyone"                                            #
strava = "faithfulathlete"                                             # URL-name or userID number
#telegram = ""                                           # username
twitter = "YourOnlyONEofcl"                                            # username; do not include @-at
twitter_creator = "@YourOnlyONEofcl"                                    # @username
twitter_site = "@YourOnlyONEofcl"                                       # @username
#vero = "youronlyone"                                               #
#wordpress = ""                                          #
youtube = "YourOnlyONEofcl"                                            # URL-name
