#facebook_authorid = ""              # template-only
#bitbucket = "techmagus"                      # username
codeberg = "techmagus"                       # username
#deviantart = "laibcoms"                     # URL-name
#ecency = "@youronlyone"                         #
#email = "contact@im.youronly.one"                          #
facebook = "YourOnly.ONE.ofcl"                       # URL-name
facebook_admin = "532996690,100042645428366,2308171266072912"                 # profile ID number and page admin to get domain insights
facebook_appid = "183794425326191"                 # app ID
facebook_authorid = "2308171266072912"              # user ID
facebook_pageid = "339301830572387"                # page ID
github = "techmagus"                         # username
gitlab = "techmagus"                         # username
#hive = "@youronlyone"                           #
instagram = "YourOnly.One"                      # username
keybase = "yukino"                        # username
keyoxide = "https://youronly.one/?verify=keyoxide"                       # URL
linkedin = "youronlyone"                       # URL-name
#linkedin_company = ""               # URL-name
mastodon = "c.im/@youronlyone"                       # example.com/@username
#medium = ""                         #
pinterest = "YourOnlyONEofcl"                      # username
#quora = ""                          # username
#reddit = "Laibcoms"                         # username
#skype = "jcjohn.sesecuneta@live.com"                          # username or email
#stackoverflow = "306674"                  # user number
#steemit = "@youronlyone"                        # @URL-name
strava = "faithfulathlete"                         # URL-name or userID number
#telegram = ""                       # URL-name
twitter = "YourOnlyONEofcl"                        # username; do not include @-at
twitter_creator = "@YourOnlyONEofcl"                # @username
twitter_site = "@YourOnlyONEofcl"                   # @username
#vero = "youronlyone"                           # URL-name
#wordpress = ""                      #
youtube = "YourOnlyONEofcl"                        # URL-name or channel ID number
