#[module]
#  [module.hugoVersion]
#    #extended = true
#    min = "0.88.0"
#    #max = ""


#######  #######  #######  #######  #######  #######  #######  #######


[social]
  #bitbucket = ""                                          #
  #deviantart = "laibcoms"                                         # URL-name
  #email = ""                                              # email address; leave empty
  facebook = "YourOnly.ONE.ofcl"                                           # URL-name
  facebook_admin = "532996690,100042645428366,2308171266072912"                                     # profile ID number and page admin to get domain insights
  facebook_appid = "183794425326191"                                     # app ID
  facebook_authorid = "2308171266072912"                                  #
  facebook_pageid = "339301830572387"                                    # FB page ID
  github = "techmagus"                                             # username
  #gitlab = ""                                             # username
  instagram = "YourOnly.One"                                          # username
  keybase = "yukino"                                            # username
  #linkedin = "youronlyone"                                           # URL-name
  #linkedin_company = ""                                   # URL-name
  mastodon = "mastodon.social/@youronlyone"                                           # example.com/@username
  #medium = ""                                             #
  #pinterest = ""                                          # username
  #quora = ""                                              # username
  #reddit = "Laibcoms"                                             # username
  #skype = ""                                              # username or email
  #stackoverflow = "306674"                                      # user number
  strava = "faithfulathlete"                                             # URL-name or userID number
  #telegram = ""                                           # username
  twitter = "YourOnlyONEofcl"                                            # username; do not include @-at
  twitter_domain = "YourOnly.One"                                     # this domain shows in twitter cards as "View on `twitter_domain`"
  twitter_creator = "@YourOnlyONEofcl"                                    # @username
  twitter_site = "@YourOnlyONEofcl"                                       # @username
  #wordpress = ""                                          #
  youtube = "YourOnlyONEofcl"                                            # URL-name


#######  #######  #######  #######  #######  #######  #######  #######
