# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "YourOnly.One Hugo Defaults"
license = "MIT"
licenselink = "https://github.com/YourOnly-One/yoo-hugo-defaults/blob/master/LICENSE"
description = "A collection of Hugo Defaults (partials, overrides, and other files) for and by YourOnly.One"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/techmagus/youronlyone-hugo-defaults"

# If you have a running demo of the theme.
#demosite = "https://gohugo.io"

tags = ["component", "feed", "rss", "output-format", "partials", "i18n", "archetypes"]
features = ["rss", "sitemap", "sitemapindex", "partials", "i18n", "archetypes"]

# If the theme has multiple authors
#authors = [
#  {name = "Name of author", homepage = "Website of author"},
#  {name = "Name of author", homepage = "Website of author"}
#]

# If the theme has a single author
[author]
  name = "YourOnly.One"
  homepage = "https://YourOnly.One"

# If porting an existing theme
#[original]
#  author = "Name of original author"
#  homepage = "His/Her website"
#  repo = "Link to source code of original theme"
